import { Message } from './chat';

export const messages: Message[] = [
  {
    id: '1',
    text: '你好',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:00:00',
  },
  {
    id: '2',
    text: '在吗？刚刚那个活动我报名成功了。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:02:00',
  },
  {
    id: '3',
    text: '太棒了！你选了哪个场次？我选的是周六下午那场。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:04:00',
  },
  {
    id: '4',
    text: '我选的也是周六下午，那正好一起去。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:06:00',
  },
  {
    id: '5',
    text: '可以，到时候我们一起集合。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:08:00',
  },
  {
    id: '6',
    text: '好的，我提前十分钟到。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:10:00',
  },
  {
    id: '7',
    text: '你喜欢飞盘多久了？',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:12:00',
  },
  {
    id: '8',
    text: '去年夏天开始接触的，主要是朋友带我去玩，后来就喜欢上了。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:14:00',
  },
  {
    id: '9',
    text: '那我们水平差不多哈哈，我也是去年才玩，还是新手。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:16:00',
  },
  {
    id: '10',
    text: '没关系，我们都是来放松和交朋友的。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:18:00',
  },
  {
    id: '11',
    text: '对，我很期待这次的活动。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:20:00',
  },
  {
    id: '12',
    text: '你平时还喜欢什么运动？',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:22:00',
  },
  {
    id: '13',
    text: '打羽毛球和骑车比较多，偶尔也去爬山。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:24:00',
  },
  {
    id: '14',
    text: '我也是！骑车我最近才开始尝试。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:26:00',
  },
  {
    id: '15',
    text: '骑上海的滨江真的很舒服，推荐给你。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:28:00',
  },
  {
    id: '16',
    text: '我一直听说过但还没去过，有机会可以一起去吗？',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:30:00',
  },
  {
    id: '17',
    text: '当然可以，最近周末都挺空的。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:32:00',
  },
  {
    id: '18',
    text: '那太好了，我们可以约一下。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:34:00',
  },
  {
    id: '19',
    text: '你住哪一块？我在徐汇这边。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:36:00',
  },
  {
    id: '20',
    text: '我在静安，其实挺近的。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:38:00',
  },
  {
    id: '21',
    text: '好巧，以后见面也方便。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:40:00',
  },
  {
    id: '22',
    text: '你对这次活动的组织怎么看？我感觉挺靠谱的。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:42:00',
  },
  {
    id: '23',
    text: '是的，流程和时间都写得清清楚楚，看起来很专业。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:44:00',
  },
  {
    id: '24',
    text: '我还特意查了天气，周末晴天，适合户外。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:46:00',
  },
  {
    id: '25',
    text: '那我们可以带点饮料和小吃过去。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:48:00',
  },
  {
    id: '26',
    text: '对，我负责水果，你带饮料吧～',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:50:00',
  },
  {
    id: '27',
    text: '成交哈哈，到时候别迟到哦～',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:52:00',
  },
  {
    id: '28',
    text: '我会准时！已经很期待和你见面了。',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:54:00',
  },
  {
    id: '29',
    text: '我也是，终于可以从线上走到线下啦。',
    isMe: true,
    avatar: 'https://qiniustatic.womenshike.top/icon-message-avatat-systems.png',
    timestamp: '2025-06-19T22:56:00',
  },
  {
    id: '30',
    text: '晚安，明天见～',
    isMe: false,
    avatar: 'https://qiniustatic.womenshike.top/placeholder_avatar_4.png',
    timestamp: '2025-06-19T22:58:00',
  },
];
